# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_loc', models.CharField(max_length=200)),
                ('caption', models.CharField(max_length=200)),
                ('hypothesis', models.CharField(max_length=200)),
                ('nhypothesis', models.CharField(max_length=200)),
            ],
        ),
    ]
